### PR TITLE
Day1 Q2

### PR DESCRIPTION
**Pull request by kshitizpriyam**

### CODE REVIEW

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
1. Move your username folder(`kshitizpriyam`) inside the `answers` folders
2. Solution to 1st problem is missing

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
1. MOVE FOLDER INSIDE THE ANSWERS FOLDER
2. Day1 -Q1 missing

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
- Day 1 - Q1
- Day 3 - All questions
- Day 4 - All questions
- Day 5 - Q2 

are missing

**Review by bhattcodes — COMMENTED** [review]
@kshitizpriyam please add the above stated questions, before the evaluation day!!

**Pull request merged**
