### PR TITLE
Day10

### PR DESCRIPTION
**Pull request by AkshajV1309**

### CODE REVIEW

**Comment by AkshajV1309** [comment]
Bro, there is a guy named Vansh Baijal who has plagarised some of  my
answers in last few days first instance being day2 and latest is today. As
there is a rule against plagiarism please look into it. Thanks.

**Comment by AkshajV1309** [comment]
[image: image.png] It's this guy I'm talking about.
[image: image.png]
[image: image.png] see here, other than removing the '=' sign which I
deliberately put to catch him although he played smart and didn't copy it;
everything is the same!

**Comment by AkshajV1309** [comment]
and Input String instead of Enter is the only other change

**Comment by Tanish2002** [comment]
@AkshajV1309 Thanks for conveying this to us we are currently investigating his solutions and will definitely take actions ASAP

**Comment by AkshajV1309** [comment]
Thanks

**Pull request merged**
