### PR TITLE
day 3 ques 1

### PR DESCRIPTION
**Pull request by ananyabhatia2002**

### CODE REVIEW

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
some solutions are missing
you have only provided solutions for Day1 and 3 - question 1

**Comment by ananyabhatia2002** [comment]
> some solutions are missing
> you have only provided solutions for Day1 and 3 - question i uploaded all, maybe some issue. I will do it again.

**Comment by Tanish2002** [comment]
> i uploaded all, maybe some issue. I will do it again.
No problem you can do it as many times as you want

**Comment by ananyabhatia2002** [comment]
> > i uploaded all, maybe some issue. I will do it again.
> 
> No problem you can do it as many times as you want

please check now for day 1 and 3

**Comment by Tanish2002** [comment]
> please check now for day 1 and 3

There are still problems, If you want help you can contact me on the codechef whatsapp group, My name is Tanish Khare

**Comment by Tanish2002** [comment]
Well Done!

**Pull request merged**
