### PR TITLE
day16

### PR DESCRIPTION
**Pull request by AnaAdler18**

### CODE REVIEW

**Comment by coderrohan14** [comment]
Expected Time Complexity is O(logn) and your code's complexity is O(n).
Try to optimize it and submit again.

**Comment by AnaAdler18** [comment]
I did binary search then how is it O(n) . Can u please explain where I went wrong ?

**Comment by coderrohan14** [comment]
> I did binary search then how is it O(n) . Can u please explain where I went wrong ?
(That's not binary search)
U just divided the length by 2 once at the start only and then you are just incrementing and decrementing by 1 .... but in binary search in each iteration, size is reduced by two which makes its complexity O(logn).

**Comment by AnaAdler18** [comment]
Oh my God, yes .Thank you . I'll send the new one soon

**Pull request merged**
