### PR TITLE
Create question 2.py

### PR DESCRIPTION
**Pull request by AnurajPariya03**

### CODE REVIEW

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
solution to the first problem is missing

**Comment by AnurajPariya03** [comment]
i am confused in it 
about the pattern

**Comment by Tanish2002** [comment]
discuss it with friends :relaxed:

**Comment by AnurajPariya03** [comment]
both done

**Comment by bhattcodes** [comment]
@AnurajPariya03 you didn't added question 1 answer, add the solution of first problem too.. so that we can merge your pull request, and make sure you follow the dir tree correctly. 
make new file path: `answers/Anuraj Pariya/Day 1/question 1.py `.

**Comment by Tanish2002** [comment]
well he added it main and made PR from a new branch :pensive:. I will add it myself this time, from next time please add both questions at the same time and then make a PR

**Pull request merged**
