### PR TITLE
Q1

### PR DESCRIPTION
**Pull request by arc03**

### CODE REVIEW

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
I don't know if you are looking at what you are doing but you need to make a file named `Q1.cpp` but you made a folder named `Q1` and inside that folder added a file `.cpp`

**Comment by Tanish2002** [comment]
Also move your folder `Archita` inside the `answers` folder

**Comment by Tanish2002** [comment]
still wrong.
1. Delete the first Archita folder
2. You need to make a folder named `Day1` and inside that add `question1.py` and `question2.py`
3. Preferably use the right extension for the program i.e `.py` for a python program and not `.txt`

**Comment by Tanish2002** [comment]
If you still don't get it then write here so I can either explain it to you again or do it myself this once as it's your first time

**Comment by arc03** [comment]
> If you still don't get it then write here so I can either explain it to you again or do it myself this once as it's your first time

Please help me I am not able to do it

**Comment by Tanish2002** [comment]
Did you delete your fork as I can't open it.
If yes then
1. Make a new fork
2. In your forked repo open the `answers` folder and create a new folder named `arc03` or `Archita`
3. In that newly made folder make a new folder named `Day1`
4. In the `Day1` folder make 2 files -> `question1.cpp` and `question2.cpp` which have your solutions
5. Finally make New PR with all these changes

For reference look at how other people are doing it, example: [here](https://github.com/Codechef-SRM-NCR-Chapter/30-DaysOfCode-March-2021/tree/main/answers/AasthaCodex/Day%201)

**Comment by Tanish2002** [comment]
I'm closing this PR
Follow these instructions and make a new PR.
For more help just ask for my contact details on the codechef whatsapp group

**Pull request closed without merging**
