### PR TITLE
Create question1.cpp

### PR DESCRIPTION
**Pull request by Ishita466**

### CODE REVIEW

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
solution to 2nd problem is missing

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
You deleted the first problem now

**Comment by Ishita466** [comment]
> You deleted the first problem now

Earlier i submitted the solution to ques.2 as ques.1 so i have renamed this as ques 2 and uploaded the ques 1 also.

**Comment by Tanish2002** [comment]
Good Job!

**Pull request merged**
