### PR TITLE
Create question1.cpp

### PR DESCRIPTION
**Pull request by thenextgoogler**

### CODE REVIEW

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
solution to 2nd problem is missing

**Comment by thenextgoogler** [comment]
> solution to 2nd problem is missing

Committed

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
Change the folder name to "DhruvPandey" as that's what you've used before
It's "Dhruv Pandey" right now

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
You didn't update correctly, question 1.cpp is empty

**Comment by Tanish2002** [comment]
Good Job!

**Pull request merged**
