### PR TITLE
Create Ananya Chandra

### PR DESCRIPTION
**Pull request by AnaAdler18**

### CODE REVIEW

**Comment by Tanish2002** [comment]
Read the README file
1. You need to make your changes inside a folder with your username inside `answers` folder
2. Don't make a PR until you haven't solved the questions

**Review by Tanish2002 — CHANGES_REQUESTED** [review]
Read the README file
1. You need to make your changes inside a folder with "your own username" inside `answers` folder
2. Don't make a PR until you have solved the questions

**Comment by AnaAdler18** [comment]
Sry i got it now . Have sent a new pull request with the answers

**Comment by Tanish2002** [comment]
No Problem, Just keep learning!

**Pull request closed without merging**
